title: Okruchy
description: (...)

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

layout: default


plugins:
  - jekyll-include-cache
